version: "3"

services:
    db:
        image: mysql:latest
        container_name: db
        ports:
            - "3306:3306"
        volumes:
            - /var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: test_csv
